#!/usr/bin/env python3
"""
Test script to demonstrate dynamic best model selection
"""

import requests
import json
import time

def test_dynamic_model_selection():
    """Test the dynamic model selection functionality"""
    
    # Login first
    print("🔐 Logging in...")
    login_data = {'username': 'admin', 'password': 'admin123'}
    
    try:
        login_response = requests.post('http://localhost:5000/auth/login', json=login_data)
        
        if login_response.status_code != 200:
            print(f"❌ Login failed: {login_response.status_code}")
            return
        
        token = login_response.json()['access_token']
        headers = {'Authorization': f'Bearer {token}'}
        
        print("✅ Login successful!\n")
        
        # Make multiple forecast requests to see different best models
        print("📊 Testing Dynamic Model Selection...")
        print("=" * 50)
        
        for i in range(5):
            forecast_data = {
                'district': 'Central Delhi', 
                'months_ahead': 6
            }
            
            response = requests.post(
                'http://localhost:5000/forecast-district', 
                json=forecast_data, 
                headers=headers
            )
            
            if response.status_code == 200:
                result = response.json()
                
                print(f"🎯 Request {i+1}:")
                print(f"   Best Model: {result['best_model'].upper()}")
                print(f"   MAE Scores: {result['model_selection']['all_models_mae']}")
                print(f"   Selection: {result['model_selection']['selection_note']}")
                print(f"   District: {result['district']}")
                print(f"   Generated by: {result['generated_by']}")
                print()
                
                # Short delay to see variations
                time.sleep(0.5)
                
            else:
                print(f"❌ Request {i+1} failed: {response.status_code}")
                if response.content:
                    print(f"Error: {response.text}")
    
    except requests.ConnectionError:
        print("❌ Cannot connect to server. Make sure the Flask app is running on http://localhost:5000")
    except Exception as e:
        print(f"❌ Error: {str(e)}")

if __name__ == "__main__":
    test_dynamic_model_selection()
